title: Volatia
description: ttpg doc
theme: just-the-docs

url: https://Dragonfrut.github.io/Volatia

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.comDragonfrut/Volatia
