title: Volatia
description: ttpg doc
theme: just-the-docs
# Color scheme supports "light" (default) and "dark"


url: https://Dragonfrut.github.io/Volatia

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.comDragonfrut/Volatia
